name: fluttercast
description: Flutter Demo Weather Application

version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite: any
  path: any
  http: ^0.12.0
  intl: ^0.16.1
  weather: ^0.9.5
  location: 2.4.0
  equatable: ^1.1.1
  flutter_bloc: ^3.2.0
  path_provider: ^1.6.5
  weather_icons: ^2.0.1
  cupertino_icons: ^0.1.2
  permission_handler: 3.1.0
  shared_preferences: ^0.5.6+2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
